[package]
name = "ws-webextensions"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen =  { version = "0.2", features = ["serde-serialize"] }
web-sys = { version = "0.3", features = ["console"] }
js-sys = "0.3"
wasm-bindgen-futures = "0.4"